# config file for downstram task

# --- General Task Configuration ---
# Task can be 'classification' or 'anomaly_detection'
task: classification
path_to_save: "/home/nvidia/workplace/contrastive_loss_res/" # Where to save plots and reports

# --- Mlflow Configuration -----
mlflow_upload: False
mlflow_name: "20251231_140014_nvidia"
mlflow_exp: "ASTRA(Downstream Tasks)"

# --- Data Paths ---
# Paths to the embeddings and labels from your pre-trained model
path_to_data: "/home/nvidia/workplace/contrastive_loss_res/run_20251231_140014/embeddings.h5"

# --- Data Sampling Configuration ---
# For no sampling, set to "None"
sampling: {
            "AGN": 1000,
            "CEP": 1000,
            "DSCT|GDOR|SXPHE": 1000,
            "RR": 1000,
            "ECL": 1000,
            "ELL": 1000,
            "LPV": 1000,
            "RS": 1000,
            "CV": 1000,
            "S": 1000,
            "SOLAR_LIKE": 1000,
            "YSO": 1000
        }

# --- Classification Task Parameters ---
classification_params:
  
  bootstrap: False    # For bootstrapping results
  n_iterations: 100   # For bootstrapping results
  test_size: 0.2
  random_state: 42
  # List of classifier models to run. Can be 'lr' (Logistic Regression) or 'rf' (Random Forest)
  models:
    - lr
    - rf

  # --- Hyperparameters for each model ---
  # These are passed directly to the scikit-learn constructors
  lr_params:
    C: 0.1
    max_iter: 1000
    solver: 'lbfgs'

  rf_params:
    n_estimators: 100
    max_depth: 25
    n_jobs: 20 # Use all available CPU cores
    min_samples_leaf: 10
    max_features: 0.1
  
  mlp_params:
    hidden_layers: [256, 128] # Two hidden layers with 256 and 128 neurons
    dropout_rate: 0.3         # Dropout rate for regularization
    learning_rate: 0.0001     # Learning rate for the Adam optimizer
    epochs: 100               # Maximum number of epochs to train for
    batch_size: 256           # Number of samples per training step
    patience: 10             # Patience for EarlyStopping




# --- Anomaly Detection Task Parameters ---
anomaly_detection_params:
  
  inspect_samples: 10   # Number of anomalies to inspect
  # List of models to run. Can be 'if' (Isolation Forest)
  models: 
    - 'if'
  
  # --- Hyperparameters for each model ---
  if_params:
    n_jobs: 10
    random_seed: 42
