# config file for downstram task

# --- General Task Configuration ---
# Task can be 'classification' or 'anomaly_detection'
task: classification
path_to_save: "/home/nvidia/workplace/dino_res/run_20260317_073711/" # Where to save plots and reports

# --- Mlflow Configuration -----
mlflow_upload: True
mlflow_name: "run_20260317_073711"
mlflow_exp: "ASTRA(Downstream Tasks)"

# --- Data Paths ---
# Paths to the embeddings and labels from your pre-trained model
# NOTE: training data and validation data is required for classification task. 
#       For anomaly detection task, only test data is required, else the training
#       data and validation data will be concatenated and used for anomaly detection model.
#       If you don't have separate test data for anomaly detection, you can comment out 
#       the 'test' path and the code will automatically concatenate the 'train' and 'val' 
#       data for anomaly detection.
path_to_data: 
  # test: "/home/nvidia/workplace/astra_storage/emb/all_dataset/finetuning/test/embeddings.h5"
  train: "/home/nvidia/workplace/dino_res/run_20260317_073711/train/embeddings.h5"
  val: "/home/nvidia/workplace/dino_res/run_20260317_073711/val/embeddings.h5"

# --- Classification Task Parameters ---
classification_params:
  
  bootstrap: False    # For bootstrapping results
  n_iterations: 100   # For bootstrapping results
  random_state: 42
  # List of classifier models to run. Can be 'lr' (Logistic Regression) , 'rf' (Random Forest), or 'mlp' (Multi-Layer Perceptron)
  models:
    - lr

  # --- Hyperparameters for each model ---
  # These are passed directly to the scikit-learn constructors
  lr_params:
    C: 0.1
    max_iter: 1000
    solver: 'lbfgs'

  rf_params:
    n_estimators: 150
    max_depth: 20
    n_jobs: 20 # Use all available CPU cores
    # min_samples_leaf: 10
    max_features: 0.35
  
  mlp_params:
    # hidden_layers: [256, 128] # Two hidden layers with 512 and 256 neurons
    # hidden_layers: None
    dropout_rate: 0.40        # Dropout rate for regularization
    learning_rate: 0.00005    # Learning rate for the Adam optimizer
    epochs: 50               # Maximum number of epochs to train for
    batch_size: 256           # Number of samples per training step
    patience: 10              # Patience for EarlyStopping




# --- Anomaly Detection Task Parameters ---
anomaly_detection_params:
  
  inspect_samples: 100   # Number of anomalies to inspect
  # List of models to run. Can be 'if' (Isolation Forest)
  models: 
    - 'if'
  
  # --- Hyperparameters for each model ---
  if_params:
    n_trees: 10000
    n_subsamples: 4096
    n_jobs: 30
    random_seed: 42
