# config file for downstram task

# --- General Task Configuration ---
# Task can be 'classification' or 'anomaly_detection'
task: classification
path_to_save: "/home/nvidia/workplace/dataset/resampled_data_120K/pre-training/" # Where to save plots and reports

# --- Mlflow Configuration -----
mlflow_upload: True
mlflow_name: "20251231_140014_nvidia"
mlflow_exp: "ASTRA(Downstream Tasks)"

# --- Data Paths ---
# Paths to the embeddings and labels from your pre-trained model
# NOTE: training data is required for all downstream tasks. 
#       Validation data is only needed for classification task.
path_to_data: 
  train: "/home/nvidia/workplace/dataset/resampled_data_120K/pre-training/train/embeddings.h5"
  val: "/home/nvidia/workplace/dataset/resampled_data_120K/pre-training/val/embeddings.h5"

# --- Classification Task Parameters ---
classification_params:
  
  bootstrap: False    # For bootstrapping results
  n_iterations: 100   # For bootstrapping results
  random_state: 42
  # List of classifier models to run. Can be 'lr' (Logistic Regression) , 'rf' (Random Forest), or 'mlp' (Multi-Layer Perceptron)
  models:
    - lr
    - rf
    - mlp

  # --- Hyperparameters for each model ---
  # These are passed directly to the scikit-learn constructors
  lr_params:
    C: 0.1
    max_iter: 1000
    solver: 'lbfgs'

  rf_params:
    n_estimators: 350
    max_depth: 50
    n_jobs: 20 # Use all available CPU cores
    min_samples_leaf: 10
    max_features: 0.35
  
  mlp_params:
    hidden_layers: [256, 128] # Two hidden layers with 512 and 256 neurons
    dropout_rate: 0.40        # Dropout rate for regularization
    learning_rate: 0.00005    # Learning rate for the Adam optimizer
    epochs: 100               # Maximum number of epochs to train for
    batch_size: 512           # Number of samples per training step
    patience: 10              # Patience for EarlyStopping




# --- Anomaly Detection Task Parameters ---
anomaly_detection_params:
  
  inspect_samples: 10   # Number of anomalies to inspect
  # List of models to run. Can be 'if' (Isolation Forest)
  models: 
    - 'if'
  
  # --- Hyperparameters for each model ---
  if_params:
    n_jobs: 10
    random_seed: 42
