# config file for finetuning
#
# --- Data set Paths ---
#
path_to_val: "/home/nvidia/workplace/dataset/resampled_data_120K/val/"
path_to_save: "/home/nvidia/workplace/k_distil_res_second_run/run_20260318_154848/"
path_to_data: "/home/nvidia/workplace/dataset/training_data/train/"
path_to_load: "/home/nvidia/workplace/k_distil_res_second_run/run_20260318_154848/"
#
# --- Finetuning parameters ---
#
# IMPORTANT: This must match the dataset's classes
label_map: {
            'AGN': {
                    'count': 4000,
                    'id': 0
                },
            
            'DSCT|GDOR|SXPHE': {
                    'count': 4000,
                    'id': 1
                },
            'ECL': {
                    'count': 4000,
                    'id': 2
                },
            'LPV': {
                    'count': 4000,
                    'id': 3
                },
            'RS': {
                    'count': 4000,
                    'id': 4
                },
            'S': {
                    'count': 4000,
                    'id': 5
                },
            'SOLAR_LIKE': {
                    'count': 4000,
                    'id': 6
                },
            'YSO': {
                    'count': 4000,
                    'id': 7
                },
            'CEP': {
                    'count': 967,
                    'id': 8
                },
            'CV': {
                    'count': 860,
                    'id': 9
                },
            'ELL': {
                'count': 4000,
                'id': 10
            },
            'RR': {
                    'count': 4000,
                    'id': 11
                }
            }

global_view_maxlens: {'g': 300, 'r': 350, 'i': 50}
lr: 0.00001             # Use a very small learning rate
batch_size: 128         # Adjust the batch_size for fine-tuning
num_gpus: 1             # # of GPU instances to use for training. Set to 0 for CPU training. (Default set to 0.)
epochs: 100             # Number of training epochs
patience: 10            # Early stopping patience
buffer_size: 50000      # Shuffle buffer size
unfreeze_layers: 2      # unfreeze the last 2 encoderLayers
