# config file for generating embeddings
#
# --- Data set Paths ---
#
path_to_load: "/home/nvidia/workplace/dino_res/run_20260317_051433/"
path_to_data: "/home/nvidia/workplace/dataset/test/val/"
path_to_save: "/home/nvidia/workplace/dino_res/run_20260317_051433/val/"
path_to_class_count: "/home/nvidia/workplace/dataset/test/val/data_stats.csv"
#
# --- Inference parameters ---
#
finetune: False      # Flag to load best finetuned weights for generating embeddings
batch_size: 10       # per-GPU Batch size (adjust based on GPU memory)/ Just a batch size for CPU training
num_gpus: 1          # # of GPU instances to use for training. Set to 0 for CPU training. (Default set to 0.)
global_view_maxlens: {'g': 250, 'r': 300, 'i': 50} # Using ANCHOR view sequence length, i.e., build_seg_len
mlflow_upload: True  # Upload the UMAP embedding plot to MLflow?
mlflow_name: "run_20260317_051433" # Set the name where you want to upload the plot
mlflow_exp: "ASTRA(Embeddings)"
#
# --- Required only when finetuning is True ---
unfreeze_layers: 2      # unfreeze the last 2 encoderLayers
# --- Label Map for the dataset used for finetuning ---
# --- Else can be ignored. --
#
label_map: {
            'AGN': {
                    'count': 4000,
                    'id': 0
                },
            
            'DSCT|GDOR|SXPHE': {
                    'count': 4000,
                    'id': 1
                },
            'ECL': {
                    'count': 4000,
                    'id': 2
                },
            'LPV': {
                    'count': 4000,
                    'id': 3
                },
            'RS': {
                    'count': 4000,
                    'id': 4
                },
            'S': {
                    'count': 4000,
                    'id': 5
                },
            'SOLAR_LIKE': {
                    'count': 4000,
                    'id': 6
                },
            'YSO': {
                    'count': 4000,
                    'id': 7
                },
            'CEP': {
                    'count': 967,
                    'id': 8
                },
            'CV': {
                    'count': 860,
                    'id': 9
                },
            'ELL': {
                'count': 4000,
                'id': 10
            },
            'RR': {
                    'count': 4000,
                    'id': 11
                }
            }
