# config file for training
#
# --- Data set Paths ---
#
path_to_read: "/home/nvidia/workplace/dataset/training_data/train"
path_to_val: "/home/nvidia/workplace/dataset/training_data/val"
path_to_save: "/home/nvidia/workplace/k_distil_res/"
#
# --- Architecture ---
#
# Provide num_global_views & num_local_views
# We have consider num_global_views = 3, i.e., (start, mid, end) windows of the light curve
# Adjust the num_local_views based on VRAM capacity.
num_global_views: 3
num_local_views: 6
#
# --- Training Hyperparameters ---
#
# NOTE: global_batch_size = batch_size * num_gpus
# So, set the batch_size accordingly.
# e.g. batch_size = 128, num_gpus = 8, therefore, global_batch_size = 1024
#
patience: 250          # Early stopping patience
epochs: 100           # Number of training epochs
buffer_size: 100000                     # Shuffle buffer size for CPU training, 100000 for GPU training.
batch_size: 78        # per-GPU Batch size (adjust based on GPU memory)/ Just a batch size for CPU training
num_gpus: 8           # # of GPU instances to use for training. Set to 0 for CPU training.
#
s_temp: 0.1
start_t_temp: 0.04
base_t_temp: 0.07
warmup_epochs_temp: 15
base_ema_m: 0.996
final_ema_m: 1.0
use_ema_scheduler: False
momentum_center: 0.9
# --- Augmentation Parameters (Global & Local Views) ---
#
#
gv_maxlens: {'g': 250, 'r': 300, 'i': 50}
lv_maxlens_list:
- {'g': 90, 'r': 100, 'i': 10}  # For LV 1, 2, 3 (Start, Mid, End)
- {'g': 50, 'r': 55, 'i': 5}   # For LV 4 (Sliding)
- {'g': 50, 'r': 60, 'i': 5}  # For LV 5 (Sliding)
- {'g': 50, 'r': 60, 'i': 10}    # For LV 6 (Sliding)
  
apply_noise_list: [True, True, True, False, False]
noise_levels_list: [0.01,   0.01,  0.009,  0.05,   0.02]
apply_binning_list: [True, True, False, True, False]
apply_outlier_list: [True, True, False, False, True]
bin_widths_list: [5,     5,    5,    5,     5]
drop_rates_list: [0.02,   0.02,  0.01,  0.01,   0.01]              
#
# --- Model Parameters ---
#
num_layers: 4          # Number of encoder layers
mjd: True              # Use MJD for positional encoding
base: 10000.0          # Base for positional encoding
d_model: 256           # Embedding dimension
num_heads: 4           # Number of attention heads
dff: 1024              # Feed-forward network dimension
rate: 0.1              # Dropout rate
use_band_info: True    # Use segment embeddings
time_scaling: 904.78   # Scaling factor for time indices in scaled positional encoding (288 * np.pi)
use_drop: False         # Use dropout
projection_dim: 65536    # Projection head dimension 

#
# --- Optimizer and Scheduler ---
#
use_custom_schedule: True
#lr = 1e-4                              # Use initial_lr in train function if not using schedule. 
scheduler_type: "cosinedecay"           # Type of learning rate scheduler (e.g., "cosinedecay", "noam")
base_lr: 0.0005                         # Base learning rate for scaling when using custom schedule.
warmup_epochs_sch: 5                   # Number of warmup steps for Noam scheduler
n_training_samples: 2073458                    # Total number of training samples 10000+3000+7500
# ---- parameters when use_custom_schedule=True -----
initial_lr: 0.001                       # initial_lr=lr, # Only if use_custom_schedule=False
# ------------------------------------------------------------------------------------
#
# --- Mlflow Configuration -----
#
mlflow_upload: True
mlflow_exp: "ASTRA_Distil"
mlflow_uri: "http://localhost:8000" 

                      