# config file for finetuning
#
# --- Data set Paths ---
#
path_to_val: "/kaggle/input/datasets/torshamajumder/distill-data-finetune/finetune_data/val/"
path_to_save: "/kaggle/working/"
path_to_data: "/kaggle/input/datasets/torshamajumder/distill-data-finetune/finetune_data/train/"
path_to_load: "/kaggle/input/models/torshamajumder/distilled-weights-v1/tensorflow1/default/1/distilled-weights/"
#
# --- Model Parameters ---
#
num_layers: 4          # Number of encoder layers
mjd: True              # Use MJD for positional encoding
base: 10000.0          # Base for positional encoding
d_model: 256           # Embedding dimension
num_heads: 4           # Number of attention heads
dff: 1024              # Feed-forward network dimension
rate: 0.1              # Dropout rate
use_band_info: True    # Use segment embeddings
time_scaling: 904.78   # Scaling factor for time indices in scaled positional encoding (288 * np.pi)
use_drop: True        # Use dropout
projection_dim: 2048    # Projection head dimension 
#
# --- label parameters ---
#
# IMPORTANT: This must match the dataset's classes
label_map: {
            'AGN': {
                    'count': 4,
                    'id': 0
                },
            
            'DSCT|GDOR|SXPHE': {
                    'count': 4,
                    'id': 1
                },
            'ECL': {
                    'count': 4,
                    'id': 2
                },
            'LPV': {
                    'count': 4,
                    'id': 3
                },
            'RS': {
                    'count': 4,
                    'id': 4
                },
            'S': {
                    'count': 5,
                    'id': 5
                },
            'SOLAR_LIKE': {
                    'count': 5,
                    'id': 6
                },
            'YSO': {
                    'count': 4,
                    'id': 7
                },
            'CEP': {
                    'count': 4,
                    'id': 8
                },
            'CV': {
                    'count': 4,
                    'id': 9
                },
            'ELL': {
                'count': 4,
                'id': 10
            },
            'RR': {
                    'count': 4,
                    'id': 11
                }
            }

global_view_maxlens: {'g': 250, 'r': 300, 'i': 50}
lr: 0.00001             # Use a very small learning rate
batch_size: 16          # Adjust the batch_size for fine-tuning
num_gpus: 1             # # of GPU instances to use for training. Set to 0 for CPU training. (Default set to 0.)
epochs: 50             # Number of training epochs
patience: 10            # Early stopping patience
buffer_size: 5000      # Shuffle buffer size
unfreeze_layers: "all"      # freeze all encoderLayers
